FROM node:21.5.0-alpine

RUN apk add --no-cache tzdata
ENV TZ=Asia/Krasnoyarsk

WORKDIR /client

COPY client/package.json ./ 

RUN npm install

COPY client/ .

CMD ["sh", "-c", "export TZ=Asia/Krasnoyarsk && npm start"]
