version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "4100:${REACT_PORT}"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./client:/client
      - /client/node_modules

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3010:${EXPRESS_PORT}"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./server:/server
      - /server/node_modules

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3210:80"
    depends_on:
      - client
      - server
