FROM node:21.5.0-alpine

RUN apk add --no-cache tzdata
ENV TZ=Asia/Krasnoyarsk

WORKDIR /server

COPY server/package.json ./ 

RUN npm install

COPY server/ .

CMD ["sh", "-c", "export TZ=Asia/Krasnoyarsk && npm run start:dev"]