const theme = {
    token: {
        colorPrimary: '#018c30',
        colorSuccess: '#52c41a', 
        colorWarning: '#faad14', 
        colorError: '#f5222d',   
        colorInfo: '#1890ff',   
    },
    components: {
        Layout: {
            bodyBg:'#f5f7fa',
            footerBg: '#fff',
            headerHeight: 41,
            headerPadding: 0,
            fontFamily: 'Futurabookc',
            siderBg: '#fafafa',
        },
        Menu: {
            fontFamily: 'Manrope',
            itemHeight: 28,
            fontSize: 13,
            itemBg: '#fafafa',
            itemSelectedBg: '#018c3011',
        },
        Sider: {
            itemBg: '#fafafa',
        },
        Button: {
            borderRadius: 3,
            borderRadiusLG: 3,
            borderRadiusSM: 3,
            fontFamily: 'Manrope',
            fontSize: 13,
            colorPrimary: '#018c30', 
            colorPrimaryHover: '#02a93a', 
            colorPrimaryActive: '#016c25',
            defaultBorderColor: '#d9d9d9',
            defaultColor: '#262626',
            defaultShadow: 'none',
            primaryShadow: 'none',
            dangerShadow: 'none',
        },
        Table: {
            fontFamily: 'Manrope',
            fontSize: 13,
            colorText: '#4A5268',
            headerBg: '#f0f2f5',
            borderColor: '#e6e6e8',
            rowHoverBg: 'rgb(245, 245, 245, 0.2)',
            colorTextHeading: '#6A7184',
            borderRadiusLG: 0,
            borderRadiusSM: 0,
            borderRadiusXS: 0,
            rowExpandedBg: '#fff',
            paddingXS: 0,
            paddingLG: 0,
            paddingSM: 0,
        },
        Pagination: {
            borderRadius: 2,
            fontFamily:  'Manrope',
        },
        Input: {
            borderRadius: 2,
            borderRadiusSM: 2,
            borderRadiusXS: 2,
            borderRadiusLG: 2,
            fontFamily: 'Manrope',
            colorPrimaryHover: '#018c30',
            activeBorderColor: '#018c30',
            hoverBorderColor: '#018c30',
            activeShadow: '0 0 0 2px rgba(1,140,48, 0.1)',
        },
        InputNumber: {
            borderRadius: 2,
            borderRadiusSM: 2,
            borderRadiusXS: 2,
            borderRadiusLG: 2,
            fontFamily: 'Manrope',
            colorPrimaryHover: '#018c30',
            activeBorderColor: '#018c30',
            hoverBorderColor: '#018c30',
            activeShadow: '0 0 0 2px rgba(1,140,48, 0.1)',
        },
        DatePicker: {
            borderRadius: 2,
            fontFamily: 'Manrope',
            colorBgContainerDisabled: '#f5f5f5',
        },
        TimePicker: {
            borderRadius: 2,
            fontFamily: 'Manrope',
            colorBgContainerDisabled: '#f5f5f5',
        },
        Modal: {
            colorBgMask: 'rgba(0,0,0,0.60)',
            borderRadiusSM: 6,
            borderRadiusLG: 6,
            fontFamily: 'Manrope',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.15)',
        },
        Empty: {
            opacityImage: 0.5
        },
        Message: {
            fontFamily: 'Manrope',
            contentPadding: '10px 16px',
            borderRadius: 6,
        },
        Collapse: {
            fontFamily: 'Manrope',
            borderRadiusLG: 6,
            headerPadding: '12px 16px',
            contentPadding: '16px',
        },
        Form: {
            fontFamily: 'Manrope',
            labelRequiredMarkColor: '#f5222d',
            labelColor: '#262626',
        },
        Grid: {
            fontFamily: 'Futurabookc',
        },
        Card: {
            fontFamily: 'Manrope',
            borderRadius: 6,
            borderRadiusLG: 6,
            borderRadiusSM: 6,
            bodyPadding: 16,
            boxShadow: '0 1px 2px rgba(0, 0, 0, 0.06)',
            actionsBg: '#fafafa',
        },
        Select: {
            fontFamily: 'Manrope',
            borderRadius: 2,
            borderRadiusSM: 2,
            borderRadiusXS: 2,
            borderRadiusLG: 2,
            optionSelectedBg: 'rgba(1,140,48, 0.1)',
            selectorBg: '#fff',
        },
        Breadcrumb: {
            lineHeight: 2,
            separatorColor: '#d9d9d9',
            fontFamily: 'Manrope',
            fontSize: 13,
        },
        Typography: {
            fontFamily: 'Manrope',
            colorTextHeading: '#262626',
        }
    }
};

export default theme;